use_frameworks!

platform :ios, '9.0'

target 'FloatingTextField_Example' do
  pod 'FloatingTextField', :path => '../'

  target 'FloatingTextField_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
